#!/bin/bash
# installing all the packages that I like.

# I honesly don't trust myself or others to update their system
sudo apt update
sudo apt dist-upgrade

#Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

# Gpart
sudo apt install gpart

# Programming 

sudo apt install snapd

#Tilix
sudo apt install tilix
sudo apt update
sudo apt install software-properties-common apt-transport-https wget

#Virtualbox
sudo apt install virtualbox

# Import the Microsoft GPG key
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -

# Add the VS Code repository
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt update
sudo apt install code

#Sound
sudo apt install pavucontrol
sudo apt install blueman

#Screenshot
sudo apt install flameshot

sudo apt update
sudo apt dist-upgrade

#Personal Bin folder
cd ~
mkdir bin
cd bin
nano update
echo "#!/bin/bash" >> update
echo "sudo apt update" >> update
echo "sudo apt dist-upgrade" >> update
echo "sudo apt autoremove"
echo "sudo apt autoclean" >> update
echo "sudo apt update" >> update
echo "sudo apt dist-upgrade" >> update
chmod +x  update
