#!/bin/bash
# Downloads and install all the packages that I like.

# I honesly don't trust myself or others to update their system
sudo apt update
sudo apt dist-upgrade

# Browsers
sudo apt install firefox
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

# Teamviewer
wget https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
sudo apt install ./teamviewer_amd64.deb

# Variety
sudo add-apt-repository ppa:peterlevi/ppa
sudo apt-get update
sudo apt-get install variety variety-slideshow

# Tweaks
sudo add-apt-repository universe
sudo apt install gnome-tweak-tool
sudo apt install $(apt search gnome-shell-extension | grep ^gnome | cut -d / -f1)

# LibreOffice
sudo apt install libreoffice libreoffice-gtk3 libreoffice-style-elementary

# Clip board
sudo apt install com.github.davidmhewitt.clipped

# Gpart
sudo apt install gpart

# I honesly don't trust myself or others to update their system
sudo apt update
sudo apt dist-upgrade
